### ISSUE TITLE
Permissive licence for packaging in bioconda

### ISSUE THREAD

**Issue by winni2k** [qasimyu/scssim#1]
Hi,
I would like to use this tool in my research. Would it be possible for this code to be made available under a free licence such as for example [GPL, BSD, or Apache2.0](https://choosealicense.com/)?  This would allow packaging and distribution of this code through [bioconda](https://bioconda.github.io/index.html) and make it easier for scientists to perform reproducible research with scssim.

Best wishes,
Winni

**Comment by qasimyu** [comment]
Hi,
I have made the code available under a free license.

**Comment by winni2k** [comment]
Thanks! I'll have a go at getting scssim into bioconda then.
